export enum PathString {
  DANG_NHAP = "dang-nhap",
  CONG_KHAI = "viec-dang-lam",
  NOI_BO = "duyet-noi-bo",
  VIEC_DU_AN = "du-an",
  VIEC_HANG_NGAY = "hang-ngay",
  VIEC_DA_XONG = "viec-da-xong",
  THEM_MOI = "them-moi",
  THEM_MOI_CONG_VIEC_DU_AN = "them-moi-viec-du-an",
  THONG_BAO = "notifications",
  TAI_KHOAN = "tai-khoan",
  CHINH_SUA = "chinh-sua",
  USERS = "quan-ly-users",
  PRICES = "quan-ly-gia",
  KHACH_HANG = "khach-hang",
  NHAN_VIEN = "nhan-vien",
  COMPANY = "company",
  CREATE_COMPANY = "them-moi-company",
  CREATE_CUSTOMER = "them-moi-khach-hang",
  CREATE_EMPLOYEE = "them-moi-nhan-vien",
  REPORT = "thong-ke",
  VIEC_CUA_DU_AN = "viec-du-an"
}
